### ISSUE TITLE
https://github.com/fennifith/Alarmio

### ISSUE THREAD

**Issue by ShamrockLee** [fennifith/Alarmio#112]
## Device Info

- Brand: `OPPO Reno`
- Model name: `CPH1917`
-ColorOS version: `V6.0`
- Android version: `Stock, hopefully.`

## Steps to Reproduce

- download the app
- set two alarms
- close the first one that rings
- samething I've missed

## Problem

App crashed.

```Java
java.lang.IllegalStateExceptionat Alarmio.java:264

java.lang.IllegalStateException: Not attached
	at com.afollestad.aesthetic.Aesthetic.getSafePrefsEditor(Aesthetic.kt:96)
	at com.afollestad.aesthetic.Aesthetic.isDark(Aesthetic.kt:120)
	at me.jfenn.alarmio.Alarmio.updateTheme(Alarmio.java:264)
	at me.jfenn.alarmio.data.preference.ThemePreferenceData$bindViewHolder$listener$1.onSunriseChanged(ThemePreferenceData.kt:80)
	at me.jfenn.alarmio.data.preference.ThemePreferenceData.bindViewHolder(ThemePreferenceData.kt:116)
	at me.jfenn.alarmio.data.preference.ThemePreferenceData.bindViewHolder(ThemePreferenceData.kt:34)
	at me.jfenn.alarmio.adapters.PreferenceAdapter.onBindViewHolder(PreferenceAdapter.java:26)
	at me.jfenn.alarmio.adapters.PreferenceAdapter.onBindViewHolder(PreferenceAdapter.java:11)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:380)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:880)
	at android.view.View.layout(View.java:20974)
	at android.view.ViewGroup.layout(ViewGroup.java:6318)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3228)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2704)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1764)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7992)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1114)
	at android.view.Choreographer.doCallbacks(Choreographer.java:925)
	at android.view.Choreographer.doFrame(Choreographer.java:852)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1100)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903
```

**Comment by bananer** [comment]
I've also experienced this crash multiple times. I think what triggered it was the second occurence of a repeating alarm. Did not touch the device after I turned alarm off the first time.

## Device Info

- Brand: `HTC`
- Model name: HTC 10 (`pme`)
- Android version: `Stock`
- Downloaded Alarmio from F-Droid
