### ISSUE TITLE
NPE in AlarmActivity - AudioManager.setStreamVolume on a null reference

### ISSUE THREAD

**Issue by fennifith** [fennifith/Alarmio#114]
This... doesn't seem possible. `getSystemService(Context.AUDIO_SERVICE)` must've returned null, then somehow `onDestroy` was called before any of the other references to audioManager were invoked? That seems improbable.

Well, a couple null checks should fix it. TODO: convert `AlarmActivity` to Kotlin, and _add null checks / behavior for every reference_ (this isn't the first NPE I've found in it)

```
java.lang.RuntimeException: Unable to destroy activity {me.jfenn.alarmio/me.jfenn.alarmio.activities.AlarmActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.AudioManager.setStreamVolume(int, int, int)' on a null object reference
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4589)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4607)
at android.app.ActivityThread.-wrap5(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719)
at android.os.Handler.dispatchMessage(Handler.java:108)
at android.os.Looper.loop(Looper.java:206)
at android.app.ActivityThread.main(ActivityThread.java:6735)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.AudioManager.setStreamVolume(int, int, int)' on a null object reference
at me.jfenn.alarmio.activities.AlarmActivity.stopAnnoyingness(AlarmActivity.java:229)
at me.jfenn.alarmio.activities.AlarmActivity.onDestroy(AlarmActivity.java:218)
at android.app.Activity.performDestroy(Activity.java:7177)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1248)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4576)
... 9 more
```

**Comment by ajayyy** [comment]
I just noticed this today. I think it's my fault. It seems it returns null when the alarm volume is zero and I didn't check for it in my new volume code. You did a null check when you used it but I didn't notice.

**Comment by fennifith** [comment]
@ajayyy No worries! I think this is more of a problem with a lack of documentation / readability than a definitive bug... converting to Kotlin should make it more clear which fields/properties can be "null" and make it a lot easier to work with, IMO.

If you'd like to create a PR for this change, you're welcome to, but I'll probably be messing around with it in a bit regardless :)

**Comment by ajayyy** [comment]
It seems you have already done what I found in https://github.com/ajayyy/Alarmio/commit/c65aa0f5dbed305e1f713fb482e1d984889a61bf, I just forgot to update my fork

**Comment by LongJohn-Silver** [comment]
Hi, this is occurring to me, too. I don't know what can be causing it, since I am not a developer, but this happens every time I turn my alarm off. Could this be related to the background image? I say this because I changed theme, and the default image on the Schedule theme is gone, so I tried to used an image from my phone, but it does not work either.
