### ISSUE TITLE
Error previewing inexistent ringtone

### ISSUE THREAD

**Issue by takase1121** [fennifith/Alarmio#139]
```
java.lang.NullPointerException at SoundData.java:100
java.lang.NullPointerException

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.Ringtone.setAudioAttributes(android.media.AudioAttributes)' on a null object reference
	at me.jfenn.alarmio.data.SoundData.preview(SoundData.java:100)
	at me.jfenn.alarmio.adapters.SoundsAdapter.lambda$onBindViewHolder$1$SoundsAdapter(SoundsAdapter.java:67)
	at me.jfenn.alarmio.adapters.-$$Lambda$SoundsAdapter$jWF8atWizW-S1VOCSjD2EZ2kY5g.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7161)
	at android.view.View.performClickInternal(View.java:7138)
	at android.view.View.access$3500(View.java:811)
	at android.view.View$PerformClick.run(View.java:27419)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

## Device Info
Android Version: 29
Device Manufacturer: Xiaomi
Device Model: Redmi 7A

## Steps to Reproduce
- add a ringtone (external file like ogg)
- delete the file 
- try to preview the file in Alarm settings

**Comment by takase1121** [comment]
I've edited this issue to include usage. This morning I was almost late because of this issue.
