### ISSUE TITLE
repeated crash log, while opening the app

### ISSUE THREAD

**Issue by machiav3lli** [fennifith/Alarmio#41]
this error happens mostly two or three times a day(I open the app mostly 6-8 times a day), I ignored it for sometime, but now I think there's maybe a real problem.
is there a more convenient way to send the logs without emailing it.
maybe instead of share, a linking to upload it to a server or something like that.
thanks.
```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{5c38390 VFED..... ......ID 0,0-1080,1775 #7f0900c9 app:id/recycler}, adapter:me.jfenn.alarmio.adapters.PreferenceAdapter@9167f24, layout:androidx.recyclerview.widget.GridLayoutManager@3294a8d, context:me.jfenn.alarmio.activities.MainActivity@1234bd5
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(ObservableFlatMap.java:265)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(ObservableFlatMap.java:572)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)
	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.onNext(ObservableRefCount.java:196)
	at io.reactivex.internal.operators.observable.ObservablePublish$PublishObserver.onNext(ObservablePublish.java:172)
	at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66)
	at com.afollestad.rxkprefs.RxkPrefs$onKeyChange$1$changeListener$1.onSharedPreferenceChanged(RxkPrefs.kt:44)
	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:489)
	at com.afollestad.aesthetic.utils.PrefsExtKt.save(PrefsExt.kt:14)
	at com.afollestad.aesthetic.Aesthetic.colorPrimary(Aesthetic.kt:126)
	at me.jfenn.alarmio.Alarmio.updateTheme(Alarmio.java:253)
	at me.jfenn.alarmio.data.preference.ThemePreferenceData$2.onSunriseChanged(ThemePreferenceData.java:78)
	at me.jfenn.alarmio.data.preference.ThemePreferenceData.bindViewHolder(ThemePreferenceData.java:114)
	at me.jfenn.alarmio.data.preference.ThemePreferenceData.bindViewHolder(ThemePreferenceData.java:33)
	at me.jfenn.alarmio.adapters.PreferenceAdapter.onBindViewHolder(PreferenceAdapter.java:26)
	at me.jfenn.alarmio.adapters.PreferenceAdapter.onBindViewHolder(PreferenceAdapter.java:11)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:232)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:888)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
	at android.view.View.layout(View.java:20676)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2810)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2337)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1478)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7373)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6723)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{5c38390 VFED..... ......ID 0,0-1080,1775 #7f0900c9 app:id/recycler}, adapter:me.jfenn.alarmio.adapters.PreferenceAdapter@9167f24, layout:androidx.recyclerview.widget.GridLayoutManager@3294a8d, context:me.jfenn.alarmio.activities.MainActivity@1234bd5
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2880)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5281)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11997)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7070)
	at me.jfenn.alarmio.fragments.SettingsFragment.accept(SettingsFragment.java:106)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 95 more
```

**Comment by fennifith** [comment]
Unfortunately emailing it or creating an issue is the easiest way to send crash logs at the moment, though I am planning to work on [Crasher/#3](https://github.com/fennifith/Crasher/issues/3) in the future which would make it a bit easier.

**Comment by fennifith** [comment]
@machiav3lli if you're up for testing, you can find the APK for the last commit here - hopefully it should fix some of these issues (or at least give me a better idea of what's going on):

https://dl.bintray.com/18jafenn90/builds/013ae313620f660784b8285ce2df90899e678dbe/app-oss-debug.apk

**Comment by machiav3lli** [comment]
it doesn't install over the old version, so I had to uninstall the old one and then install the new one, maybe you should use a higher Version for the later test builds. I'll be reporting as soon as I get a crash or in three days if I don't. maybe you can implement the clock shortcut we talked about here [https://github.com/fennifith/Alarmio/issues/34] in the next test build.
and maybe you can make a public Telegram group for reporting issues and discussing the app.

**Comment by fennifith** [comment]
@machiav3lli sorry about that, it's a debug build so it will have a different signature from the release APKs. I will not be making a Telegram group, there is a Discord server [here](https://discord.jfenn.me/) for that purpose.

**Comment by machiav3lli** [comment]
One suggestion about the UI, maybe it's better keeping the red switches even in the AMOLED theme.
And one notice, the timer does send a continuous notification every second while counting down, maybe you should change it's preset (notifications-)behaviour or disable this continuous notifying. thanks

**Comment by fennifith** [comment]
@machiav3lli The continuous notification is necessary to keep the application from being automatically killed by the system when the user leaves the page (reference: [services overview](https://developer.android.com/guide/components/services)). If you do not want a notification, you can cancel the timer before leaving the app. If you have other suggestions, please open them in a separate issue to avoid digressing too far from the original topic.

**Comment by machiav3lli** [comment]
I think that the permission **ignore battery-optimisations** is enough to keep the app from being killed and it did at least work for me (doing timers mostly 20-50 minutes). and sorry for mixing things up

**Comment by machiav3lli** [comment]
happy to report that I didn't have any crash since I started using the debug version you sent before. thanks
